-- describe("Header filter test suite", function()
--     local filter
--     setup(
--       function()
--         filter = require "header_filter"
--       end
--     )

--     teardown(
--       function()
--         filter = nil
--       end
--     )
--     it("Test with upstream URL nil", function()
--       local lhs = ""
--       local rhs = filter.execute(lhs, nil, "http://downstream.com")
--       assert.same(lhs, rhs)
--     end)
--   end
-- )
